name: Check Code Formatting (uv)

on:
  pull_request:
    branches: [ main ]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12
          enable-cache: true

      # Install the clang-format tool and expose it on PATH
      - name: Install clang-format tool
        run: |
          uv tool install clang-format
          echo "$(uv tool dir --bin)" >> "$GITHUB_PATH"

      - run: ./check-format.sh
